apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice
  namespace: default
spec:
  selector:
    matchLabels:
      app: juice
  replicas: 3
  template:
    metadata:
      labels:
        app: juice
    spec:
      containers:
        - name: juice
          image: >-
            bkimminich/juice-shop:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    akc.radware.com/lb-algo: leastconns
    akc.radware.com/lb-health-check: http
  labels:
    AlteonDevice: "true"
  name: juice
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: juice
  type: LoadBalancer

