---
# tasks file for kubernetes_worker
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes
  tags:
    - pre_requisites

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  tags:
    - pre_requisites

- name: Remove Keyrings Directory (if it exists)
  ansible.builtin.shell: rm -rf /etc/apt/keyrings
  tags:
    - pre_requisites

- name: Remove Existing Kubernetes Directory (if it exists)
  ansible.builtin.shell: sudo rm -rf /etc/apt/sources.list.d/pkgs_k8s_io_core_stable_v1_32_deb.list
  tags:
    - pre_requisites

- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  tags:
    - pre_requisites

- name: Ensure swap is disabled on boot
  ansible.builtin.command:
    cmd: sudo sed -i -e '/\/swap.img\s\+none\s\+swap\s\+sw\s\+0\s\+0/s/^/#/' /etc/fstab
  tags:
    - pre_requisites

- name: Add kernel modules for Containerd
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  tags:
    - pre_requisites

- name: Load kernel modules for Containerd
  ansible.builtin.shell:
    cmd: modprobe overlay && modprobe br_netfilter
  become: true
  tags:
    - pre_requisites

- name: Add kernel parameters for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  tags:
    - pre_requisites

- name: Load kernel parameter changes
  ansible.builtin.command:
    cmd: sudo sysctl --system
  tags:
    - pre_requisites

- name: Configuring Containerd (building the configuration file)
  ansible.builtin.command:
    cmd: sudo sh -c "containerd config default > /opt/containerd/config.toml"
  tags:
    - pre_requisites

- name: Configuring Containerd (Setting SystemdCgroup Variable to True)
  ansible.builtin.command:
    cmd: sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /opt/containerd/config.toml
  tags:
    - pre_requisites

- name: Reload systemd configuration
  ansible.builtin.command:
    cmd: systemctl daemon-reload
  tags:
    - pre_requisites

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted
  tags:
    - pre_requisites

- name: Allow 6443/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 6443/tcp
  tags:
    - pre_requisites

- name: Allow 2379:2380/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 2379:2380/tcp
  tags:
    - pre_requisites

- name: Allow 22/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 22/tcp
  tags:
    - pre_requisites

- name: Allow 8080/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 8080/tcp
  tags:
    - pre_requisites

- name: Allow 10250/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 10250/tcp
  tags:
    - pre_requisites

- name: Allow 10251/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 10251/tcp
  tags:
    - pre_requisites

- name: Allow 10252/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 10252/tcp
  tags:
    - pre_requisites

- name: Allow 10255/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 10255/tcp
  tags:
    - pre_requisites

- name: Allow 5473/tcp through firewall
  ansible.builtin.command:
    cmd: sudo ufw allow 5473/tcp
  tags:
    - pre_requisites

- name: Enable the firewall
  ansible.builtin.ufw:
    state: enabled
  tags:
    - pre_requisites

- name: Reload the firewall
  ansible.builtin.command:
    cmd: sudo ufw reload
  tags:
    - pre_requisites

- name: Prepare keyrings directory and update permissions
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - pre_requisites

- name: Download Kubernetes GPG key securely
  ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  tags:
    - pre_requisites

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
  tags:
    - pre_requisites

- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  tags:
    - pre_requisites

- name: Hold kubelet, kubeadm, kubectl packages
  ansible.builtin.command:
    cmd: sudo apt-mark hold kubelet kubeadm kubectl
  tags:
    - pre_requisites

- name: Replace /etc/default/kubelet contents
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: 'KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs"'
  tags:
    - pre_requisites

- name: Reload systemd configuration
  ansible.builtin.command:
    cmd: systemctl daemon-reload
  tags:
    - pre_requisites

- name: Restart kubelet service
  ansible.builtin.service:
    name: kubelet
    state: restarted
  tags:
    - pre_requisites

- name: Reboot the system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for Kubernetes setup"
    reboot_timeout: 150
  tags:
    - pre_requisites

- name: Copy join-command file to worker nodes
  copy:
    src: /tmp/join-command
    dest: /tmp/join-command
    mode: 0755

- name: Join Worker Nodes
  ansible.builtin.shell: sh /tmp/join-command
  become: yes

- name: Wait for all Kubernetes nodes to become Ready
  ansible.builtin.shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf wait node --all --for=condition=Ready --timeout=300s
  delegate_to: cluster-1-master-1
  run_once: true

