---
- name: Configure Kubernetes Master
  hosts: master_nodes
  become: yes
  roles:
    - kubernetes_master

- name: Configure Kubernetes Network
  hosts: master_nodes
  become: yes
  roles:
    - kubernetes_network

- name: Configure Kubernetes Worker
  hosts: worker_nodes
  become: yes
  roles:
    - kubernetes_worker

- name: Configure Kubernetes Context For Both Clusters
  hosts: master_nodes
  become: yes
  roles:
    - kubernetes_create_contexts

- name: Configure Kubernetes Metal-LB
  hosts: master_nodes
  become: yes
  roles:
    - kubernetes_metal_lb

